"""Added Supplier & Shipment models

Revision ID: 171ee2322893
Revises: e3bf02a0f023
Create Date: 2025-03-22 11:42:09.990275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '171ee2322893'
down_revision = 'e3bf02a0f023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment', schema=None) as batch_op:
        batch_op.alter_column('estimated_delivery',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment', schema=None) as batch_op:
        batch_op.alter_column('estimated_delivery',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
