"""Added logistics tables

Revision ID: 58fb9824e6fb
Revises: 171ee2322893
Create Date: 2025-03-22 12:18:04.544431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58fb9824e6fb'
down_revision = '171ee2322893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment', schema=None) as batch_op:
        batch_op.alter_column('estimated_delivery',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=200), nullable=False))

    with op.batch_alter_table('shipment', schema=None) as batch_op:
        batch_op.alter_column('estimated_delivery',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
