"""Added estimated_delivery column

Revision ID: bb5e8e1ef5fe
Revises: 
Create Date: 2025-03-22 08:14:41.152491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb5e8e1ef5fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restock_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_delivery', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restock_request', schema=None) as batch_op:
        batch_op.drop_column('estimated_delivery')

    # ### end Alembic commands ###
