"""Added delivery_time to Supplier

Revision ID: e3bf02a0f023
Revises: 9b1c0de34112
Create Date: 2025-03-22 11:36:19.004482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3bf02a0f023'
down_revision = '9b1c0de34112'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_time', sa.Integer(), nullable=False))
        batch_op.alter_column('contact_info',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.alter_column('contact_info',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('delivery_time')

    # ### end Alembic commands ###
